[package]
name = "datez"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.0"
bevy_app = "0.16.0"
bevy_ecs = "0.16.0"
jiff = "0.2.14"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
